### ISSUE TITLE
Several 9.2 missions still fail, Desert Scavengers dump

### ISSUE THREAD

**Issue by theruan** [hythloday/VenturePlanSoDMissions#75] opened 2022-03-17 21:38 UTC
The mission was sent using the following formation:
Top left: Trapper Top middle: Trapper Top right: Trapper
Down left: Tender Down right: Te'zan
Extra info: I'm using all fixes up to last in Divergentcurl Fork

___
07:51 --------------------------------------
07:51 Dump: value=C_Garrison.GetMissionDeploymentInfo(CovenantMissionFrame:GetMissionPage().missionInfo.missionID)
07:51 [1]={
07:51   locTextureKit="GarrMissionLocation-ZerethMortis",
07:51   isExhausting=false,
07:51   location="Zereth Mortis",
07:51   xp=500,
07:51   enemies={
07:51     [1]={
07:51       autoCombatAutoAttack={
07:51         description="Deal attack damage to the closest enemy.",
07:51         autoCombatSpellID=11,
07:51         duration=0,
07:51         previewMask=0,
07:51         name="Auto Attack",
07:51         hasThornsEffect=false,
07:51         schoolMask=1,
07:51         icon=1064261,
07:51         cooldown=0,
07:51         spellTutorialFlag=1
07:51       },
07:51       isElite=false,
07:51       scale=1,
07:51       portraitFileDataID=3852857,
07:51       autoCombatSpells={
07:51         [1]={
07:51           description="A violent attempt to draw anima directly from their foe, dealing 85 Arcane damage to all enemies in melee.",
07:51           autoCombatSpellID=360,
07:51           duration=0,
07:51           previewMask=0,
07:51           name="Anima Draw",
07:51           hasThornsEffect=false,
07:51           schoolMask=64,
07:51           icon=3528281,
07:51           cooldown=3,
07:51           spellTutorialFlag=3
07:51         }
07:51       },
07:51       mechanics={
07:51       },
07:51       health=2100,
07:51       role=1,
07:51       name="Engorged Mite",
07:51       boardIndex=9,
07:51       height=1,
07:51       displayID=101922,
07:51       maxHealth=2100,
07:51       attack=170
07:51     },
07:51     [2]={
07:51       autoCombatAutoAttack={
07:51         description="Deal attack damage to the closest enemy.",
07:51         autoCombatSpellID=11,
07:51         duration=0,
07:51         previewMask=0,
07:51         name="Auto Attack",
07:51         hasThornsEffect=false,
07:51         schoolMask=1,
07:51         icon=1064261,
07:51         cooldown=0,
07:51         spellTutorialFlag=1
07:51       },
07:51       isElite=false,
07:51       scale=1,
07:51       portraitFileDataID=3852857,
07:51       autoCombatSpells={
07:51         [1]={
07:51           description="A violent attempt to draw anima directly from their foe, dealing 85 Arcane damage to all enemies in melee.",
07:51           autoCombatSpellID=360,
07:51           duration=0,
07:51           previewMask=0,
07:51           name="Anima Draw",
07:51           hasThornsEffect=false,
07:51           schoolMask=64,
07:51           icon=3528281,
07:51           cooldown=3,
07:51           spellTutorialFlag=3
07:51         }
07:51       },
07:51       mechanics={
07:51       },
07:51       health=2100,
07:51       role=1,
07:51       name="Engorged Mite",
07:51       boardIndex=12,
07:51       height=1,
07:51       displayID=101922,
07:51       maxHealth=2100,
07:51       attack=170
07:51     },
07:51     [3]={
07:51       autoCombatAutoAttack={
07:51         description="Deal attack damage to the closest enemy.",
07:51         autoCombatSpellID=11,
07:51         duration=0,
07:51         previewMask=0,
07:51         name="Auto Attack",
07:51         hasThornsEffect=false,
07:51         schoolMask=1,
07:51         icon=1064261,
07:51         cooldown=0,
07:51         spellTutorialFlag=1
07:51       },
07:51       isElite=false,
07:51       scale=1.2000000476837,
07:51       portraitFileDataID=4183227,
07:51       autoCombatSpells={
07:51         [1]={
07:51           description="Lets out a snarling howl, inspiring their pack mates, increasing their damage by 10% for two turns.",
07:51           autoCombatSpellID=363,
07:51           duration=2,
07:51           previewMask=4,
07:51           name="Pack Instincts",
07:51           hasThornsEffect=false,
07:51           schoolMask=8,
07:51           icon=132214,
07:51           cooldown=5,
07:51           spellTutorialFlag=0
07:51         }
07:51       },
07:51       mechanics={
07:51       },
07:51       health=4400,
07:51       role=1,
07:51       name="Warped Pack Hunter",
07:51       boardIndex=6,
07:51       height=0.5,
07:51       displayID=101919,
07:51       maxHealth=4400,
07:51       attack=255
07:51     },
07:51     [4]={
07:51       autoCombatAutoAttack={
07:51         description="Deal attack damage to the closest enemy.",
07:51         autoCombatSpellID=11,
07:51         duration=0,
07:51         previewMask=0,
07:51         name="Auto Attack",
07:51         hasThornsEffect=false,
07:51         schoolMask=1,
07:51         icon=1064261,
07:51         cooldown=0,
07:51         spellTutorialFlag=1
07:51       },
07:51       isElite=false,
07:51       scale=1.2000000476837,
07:51       portraitFileDataID=4183227,
07:51       autoCombatSpells={
07:51         [1]={
07:51           description="Lets out a snarling howl, inspiring their pack mates, increasing their damage by 10% for two turns.",
07:51           autoCombatSpellID=363,
07:51           duration=2,
07:51           previewMask=4,
07:51           name="Pack Instincts",
07:51           hasThornsEffect=false,
07:51           schoolMask=8,
07:51           icon=132214,
07:51           cooldown=5,
07:51           spellTutorialFlag=0
07:51         }
07:51       },
07:51       mechanics={
07:51       },
07:51       health=4400,
07:51       role=1,
07:51       name="Warped Pack Hunter",
07:51       boardIndex=7,
07:51       height=0.5,
07:51       displayID=101919,
07:51       maxHealth=4400,
07:51       attack=255
07:51     },
07:51     [5]={
07:51       autoCombatAutoAttack={
07:51         description="Deal attack damage to the closest enemy.",
07:51         autoCombatSpellID=11,
07:51         duration=0,
07:51         previewMask=0,
07:51         name="Auto Attack",
07:51         hasThornsEffect=false,
07:51         schoolMask=1,
07:51         icon=1064261,
07:51         cooldown=0,
07:51         spellTutorialFlag=1
07:51       },
07:51       isElite=false,
07:51       scale=1.2000000476837,
07:51       portraitFileDataID=4183227,
07:51       autoCombatSpells={
07:51         [1]={
07:51           description="Lets out a snarling howl, inspiring their pack mates, increasing their damage by 10% for two turns.",
07:51           autoCombatSpellID=363,
07:51           duration=2,
07:51           previewMask=4,
07:51           name="Pack Instincts",
07:51           hasThornsEffect=false,
07:51           schoolMask=8,
07:51           icon=132214,
07:51           cooldown=5,
07:51           spellTutorialFlag=0
07:51         }
07:51       },
07:51       mechanics={
07:51       },
07:51       health=4400,
07:51       role=1,
07:51       name="Warped Pack Hunter",
07:51       boardIndex=5,
07:51       height=0.5,
07:51       displayID=101919,
07:51       maxHealth=4400,
07:51       attack=255
07:51     },
07:51     [6]={
07:51       autoCombatAutoAttack={
07:51         description="Deal attack damage to the closest enemy.",
07:51         autoCombatSpellID=11,
07:51         duration=0,
07:51         previewMask=0,
07:51         name="Auto Attack",
07:51         hasThornsEffect=false,
07:51         schoolMask=1,
07:51         icon=1064261,
07:51         cooldown=0,
07:51         spellTutorialFlag=1
07:51       },
07:51       isElite=false,
07:51       scale=1.2000000476837,
07:51       portraitFileDataID=4183227,
07:51       autoCombatSpells={
07:51         [1]={
07:51           description="Lets out a snarling howl, inspiring their pack mates, increasing their damage by 10% for two turns.",
07:51           autoCombatSpellID=363,
07:51           duration=2,
07:51           previewMask=4,
07:51           name="Pack Instincts",
07:51           hasThornsEffect=false,
07:51           schoolMask=8,
07:51           icon=132214,
07:51           cooldown=5,
07:51           spellTutorialFlag=0
07:51         }
07:51       },
07:51       mechanics={
07:51       },
07:51       health=4400,
07:51       role=1,
07:51       name="Warped Pack Hunter",
07:51       boardIndex=8,
07:51       height=0.5,
07:51       displayID=101919,
07:51       maxHealth=4400,
07:51       attack=255
07:51     }
07:51   }
07:51 }

**Comment by zealvurte** [comment] 2022-03-17 22:29
Without a log, I can't tell exactly what is wrong and verify this. See #43 if you wish to output logs.

Based on the deployment info dump you've provided, the known issues with VP's healing and targeting logic that are not addressed by this addon are likely reasons for incorrect sim results.

**Comment by theruan** [comment] 2022-03-18 03:10
Ty, i will check on that, i was looking for a way to do so, 1~2 days i will try to gather every mission that is failing with logs.

**Comment by theruan** [comment] 2022-03-18 21:59
[Overgrown Terror.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8307827/Overgrown.Terror.lua.log)
[Prison Break.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8307828/Prison.Break.lua.log)
[Stablizing the Geomentals.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8307829/Stablizing.the.Geomentals.lua.log)
[Desert Scavengers.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8307830/Desert.Scavengers.lua.log)
[Into the Wilds.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8307831/Into.the.Wilds.lua.log)

**Comment by theruan** [comment] 2022-03-19 08:49
[Defensive Trials.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8308853/Defensive.Trials.lua.log)

**Comment by theruan** [comment] 2022-03-19 09:31
[Marvellous Machinations.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8308889/Marvellous.Machinations.lua.log)
[Construction Error.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8308899/Construction.Error.lua.log)

[Stablizing the Geomentals 2.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8308894/Stablizing.the.Geomentals.2.lua.log)

**Comment by theruan** [comment] 2022-03-19 22:01
[Automa Attack.lua.log](https://github.com/hythloday/VenturePlanSoDMissions/files/8310206/Automa.Attack.lua.log)

**Comment by zealvurte** [comment] 2022-03-20 02:19
I'm not able to check so many logs at the moment, but I can at least confirm from your Desert Scavengers log that the healing logic in VP* is a cause for the incorrect sims of that one. This is likely the cause of most of your incorrect sims for your other logs, and isn't something this addon can fix for you.

_* any time one of your followers has a heal off cooldown, VP assumes it will cast it, even when it can't heal anyone, so it may consider it already on cooldown on a turn when it does actually cast the heal_

**Comment by theruan** [comment] 2022-03-20 10:01
then gonna try to use formations with more trappers even if the follower comes back with more damage taken.

**Closed as completed** 2023-07-27 17:15 UTC
